local harness = require("plenary.test_harness")

describe("uri.parse", function()
	local uri

	before_each(function()
		uri = require("seamless.uri")
	end)

	describe("scp:// URIs", function()
		it("parses scp://host//absolute/path", function()
			local result, err = uri.parse("scp://myserver//etc/nginx/nginx.conf")
			assert.is.Nil(err)
			assert.are.same("scp", result.scheme)
			assert.is.Nil(result.user)
			assert.are.same("myserver", result.host)
			assert.is.Nil(result.port)
			assert.are.same("/etc/nginx/nginx.conf", result.path)
			assert.are.same("scp://myserver//etc/nginx/nginx.conf", result.raw)
		end)

		it("parses scp://user@host//absolute/path", function()
			local result, err = uri.parse("scp://john@myserver//etc/hosts")
			assert.is.Nil(err)
			assert.are.same("scp", result.scheme)
			assert.are.same("john", result.user)
			assert.are.same("myserver", result.host)
			assert.is.Nil(result.port)
			assert.are.same("/etc/hosts", result.path)
		end)

		it("parses scp://user@host:2222//absolute/path", function()
			local result, err = uri.parse("scp://john@myserver:2222//etc/hosts")
			assert.is.Nil(err)
			assert.are.same("scp", result.scheme)
			assert.are.same("john", result.user)
			assert.are.same("myserver", result.host)
			assert.are.same("2222", result.port)
			assert.are.same("/etc/hosts", result.path)
		end)

		it("parses scp://host:2222//absolute/path without user", function()
			local result, err = uri.parse("scp://myserver:2222//var/log/syslog")
			assert.is.Nil(err)
			assert.are.same("scp", result.scheme)
			assert.is.Nil(result.user)
			assert.are.same("myserver", result.host)
			assert.are.same("2222", result.port)
			assert.are.same("/var/log/syslog", result.path)
		end)

		it("parses scp://host/relative/path with single slash", function()
			local result, err = uri.parse("scp://myserver/relative/path")
			assert.is.Nil(err)
			assert.are.same("myserver", result.host)
			assert.are.same("/relative/path", result.path)
		end)

		it("parses scp://host// root path", function()
			local result, err = uri.parse("scp://myserver//")
			assert.is.Nil(err)
			assert.are.same("myserver", result.host)
			assert.are.same("/", result.path)
		end)

		it("parses scp://user@host//path with no port", function()
			local result, err = uri.parse("scp://alice@backup-server//data/backup.sql")
			assert.is.Nil(err)
			assert.are.same("scp", result.scheme)
			assert.are.same("alice", result.user)
			assert.are.same("backup-server", result.host)
			assert.is.Nil(result.port)
			assert.are.same("/data/backup.sql", result.path)
		end)

		it("parses scp://host with empty user@", function()
			local result, err = uri.parse("scp://@myserver//path")
			assert.is.Nil(err)
			assert.are.same("scp", result.scheme)
			assert.is.Nil(result.user)
			assert.are.same("myserver", result.host)
		end)
	end)

	describe("sftp:// URIs", function()
		it("parses sftp://host//absolute/path", function()
			local result, err = uri.parse("sftp://fileserver//home/user/docs/file.txt")
			assert.is.Nil(err)
			assert.are.same("sftp", result.scheme)
			assert.is.Nil(result.user)
			assert.are.same("fileserver", result.host)
			assert.is.Nil(result.port)
			assert.are.same("/home/user/docs/file.txt", result.path)
		end)

		it("parses sftp://user@host//path", function()
			local result, err = uri.parse("sftp://alice@server42//opt/data")
			assert.is.Nil(err)
			assert.are.same("sftp", result.scheme)
			assert.are.same("alice", result.user)
			assert.are.same("server42", result.host)
			assert.are.same("/opt/data", result.path)
		end)

		it("parses sftp://user@host:2222//path", function()
			local result, err = uri.parse("sftp://bob@remote:2222//var/www/index.html")
			assert.is.Nil(err)
			assert.are.same("sftp", result.scheme)
			assert.are.same("bob", result.user)
			assert.are.same("remote", result.host)
			assert.are.same("2222", result.port)
			assert.are.same("/var/www/index.html", result.path)
		end)
	end)

	describe("host:port:/path format (trailing colon before path)", function()
		it("parses scp://host:2222:/path with trailing colon between port and path", function()
			local result, err = uri.parse("scp://myserver:2222:/path/to/file")
			assert.is.Nil(err)
			assert.are.same("scp", result.scheme)
			assert.are.same("myserver", result.host)
			assert.are.same("2222", result.port)
			assert.are.same("/path/to/file", result.path)
		end)

		it("parses the equivalent host:port/path without trailing colon", function()
			local result, err = uri.parse("scp://myserver:2222/path/to/file")
			assert.is.Nil(err)
			assert.are.same("myserver", result.host)
			assert.are.same("2222", result.port)
			assert.are.same("/path/to/file", result.path)
		end)
	end)

	describe("error handling", function()
		it("returns error for nil input", function()
			local result, err = uri.parse(nil)
			assert.is.Nil(result)
			assert.are.same("URI must be a non-empty string", err)
		end)

		it("returns error for non-string input", function()
			local result, err = uri.parse(123)
			assert.is.Nil(result)
			assert.are.same("URI must be a non-empty string", err)
		end)

		it("returns error for boolean input", function()
			local result, err = uri.parse(true)
			assert.is.Nil(result)
			assert.are.same("URI must be a non-empty string", err)
		end)

		it("returns error for empty string", function()
			local result, err = uri.parse("")
			assert.is.Nil(result)
			assert.is.truthy(err)
			assert.is.truthy(err:find("unsupported protocol"))
		end)

		it("returns error for unsupported protocol (http)", function()
			local result, err = uri.parse("http://myserver//path")
			assert.is.Nil(result)
			assert.is.truthy(err)
			assert.is.truthy(err:find("unsupported protocol"))
			assert.is.truthy(err:find("http"))
		end)

		it("returns error for unsupported protocol (ftp)", function()
			local result, err = uri.parse("ftp://myserver//path")
			assert.is.Nil(result)
			assert.is.truthy(err)
			assert.is.truthy(err:find("unsupported protocol"))
		end)

		it("returns error for unsupported protocol (rsync)", function()
			local result, err = uri.parse("rsync://myserver//path")
			assert.is.Nil(result)
			assert.is.truthy(err)
			assert.is.truthy(err:find("unsupported protocol"))
		end)

		it("returns error for URI with no path component", function()
			-- Pattern (/.*)$ requires a / after the host, so this fails
			local result, err = uri.parse("scp://myserver")
			assert.is.Nil(result)
			assert.is.truthy(err)
		end)

		it("returns error for URI with only scheme and slashes", function()
			-- The pattern can't match ///// because [^:/]+ needs at least one
			-- non-slash, non-colon char for the host
			local result, err = uri.parse("scp://///just/slashes")
			assert.is.Nil(result)
			assert.is.truthy(err)
		end)

		it("returns error for malformed URI with no host", function()
			local result, err = uri.parse("scp://:2222//path")
			assert.is.Nil(result)
			assert.is.truthy(err)
		end)
	end)

	describe("edge cases", function()
		it("handles trailing slash in path", function()
			local result, err = uri.parse("scp://myserver//var/log/")
			assert.is.Nil(err)
			assert.are.same("myserver", result.host)
			assert.are.same("/var/log/", result.path)
		end)

		it("handles hostname with dots", function()
			local result, err = uri.parse("scp://my.host.name//path/to/file")
			assert.is.Nil(err)
			assert.are.same("my.host.name", result.host)
			assert.are.same("/path/to/file", result.path)
		end)

		it("handles hostname with dashes", function()
			local result, err = uri.parse("scp://my-server-01//path")
			assert.is.Nil(err)
			assert.are.same("my-server-01", result.host)
			assert.are.same("/path", result.path)
		end)

		it("handles hostname with dots and dashes", function()
			local result, err = uri.parse("scp://backup-01.internal.net//data/db.dump")
			assert.is.Nil(err)
			assert.are.same("backup-01.internal.net", result.host)
			assert.are.same("/data/db.dump", result.path)
		end)

		it("preserves query-like parts in the path", function()
			local result, err = uri.parse("scp://myserver//path/to/file?version=2")
			assert.is.Nil(err)
			assert.are.same("/path/to/file?version=2", result.path)
		end)

		it("preserves fragment-like parts in the path", function()
			local result, err = uri.parse("scp://myserver//path/to/file#section")
			assert.is.Nil(err)
			assert.are.same("/path/to/file#section", result.path)
		end)

		it("handles deeply nested paths", function()
			local result, err = uri.parse("scp://myserver//a/b/c/d/e/f/g/file.txt")
			assert.is.Nil(err)
			assert.are.same("myserver", result.host)
			assert.are.same("/a/b/c/d/e/f/g/file.txt", result.path)
		end)

		it("handles port 0 as a valid port string", function()
			-- %d* matches "0" as a valid digit sequence
			local result, err = uri.parse("scp://myserver:0//path")
			assert.is.Nil(err)
			assert.are.same("0", result.port)
		end)

		it("handles single-file path at root level", function()
			local result, err = uri.parse("scp://myserver//file.txt")
			assert.is.Nil(err)
			assert.are.same("/file.txt", result.path)
		end)
	end)

	describe("return table structure", function()
		it("returns a table with all required keys", function()
			local result = uri.parse("scp://myserver//path")
			assert.is.table(result)
			assert.is.string(result.scheme)
			assert.is.string(result.host)
			assert.is.string(result.path)
			assert.is.string(result.raw)
		end)

		it("does not contain unexpected keys", function()
			local result = uri.parse("scp://myserver//path")
			assert.are.same(result.scheme, result.scheme)
			assert.are.same(result.host, result.host)
			assert.are.same(result.path, result.path)
			assert.are.same(result.raw, result.raw)
			-- user and port are optional and may be nil
		end)
	end)
end)
